name:                instrumentor
version:             0.1.0.0
github:              "andrew-wja/instrumentor"
license:             BSD3
author:              "Andrew Anderson"
maintainer:          "aanderso@tcd.ie"
copyright:           "2021 Andrew Anderson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/githubuser/instrumentor#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - llvm-hs
    - llvm-hs-pure
    - llvm-hs-pretty
    - mtl
    - text
    - optparse-applicative

executables:
  instrumentor:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - bytestring
    - instrumentor
    - llvm-hs
    - with-utf8
    - optparse-applicative
