name:                instrumentor
version:             9.0.1.0
github:              "andrew-wja/instrumentor"
license:             BSD3
author:              "Andrew Anderson"
maintainer:          "aanderso@tcd.ie"
copyright:           "2021 Andrew Anderson"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/andrew-wja/instrumentor#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - llvm-hs
    - llvm-hs-pure
    - mtl
    - text
    - optparse-applicative

executables:
  instrumentor:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - bytestring
    - instrumentor
    - llvm-hs
    - with-utf8
    - optparse-applicative
