resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/9.yaml

packages:
- .
- ./llvm-hs/llvm-hs
- ./llvm-hs/llvm-hs-pure

ghc-options:
    "$locals": -Wall
    "$targets": -Werror
    "$everything": -O3 -fllvm

extra-deps:
  - git: https://github.com/llvm/llvm-project.git
    commit: d28af7c654d8db0b68c175db5ce212d74fb5e9bc # release/12.x
  - git: https://github.com/llvm-hs/llvm-hs.git
    commit: 24ddfdf45f69bbe94ec0c97c7d4faae4a0ed205f # llvm-12-unstable

# extra-lib-dirs: [/path/to/dir]
