resolver: lts-16.31
compiler: ghc-8.8.4
compiler-check: match-exact

packages:
- .
- ./llvm-hs/llvm-hs
- ./llvm-hs/llvm-hs-pure
- ./llvm-hs-pretty

ghc-options:
  "$locals": -Wall
  "$targets": -Wall -Wno-partial-type-signatures
  "$everything": -O0

extra-lib-dirs: [ llvm-root/lib ]

extra-include-dirs: [ llvm-root/include ]

allow-newer: true

rebuild-ghc-options: true
