resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/9.yaml

packages:
- .
- ./llvm-hs/llvm-hs
- ./llvm-hs/llvm-hs-pure
- ./llvm-hs-pretty

ghc-options:
    "$locals": -Wall
    "$targets": -Wall
    "$everything": -O0

extra-lib-dirs: [ llvm-root/lib ]

extra-include-dirs: [ llvm-root/include ]
