resolver: lts-17.12

packages:
- .
- ./llvm-hs/llvm-hs
- ./llvm-hs/llvm-hs-pure

ghc-options:
  "$locals": -Wall -Wno-name-shadowing -Wno-orphans -Wno-unused-imports
  "$targets": -Wall -Wno-partial-type-signatures
  "$everything": -O2

extra-lib-dirs: [ llvm-root/lib ]

extra-include-dirs: [ llvm-root/include ]

allow-newer: true

rebuild-ghc-options: true
